[package]
name = "crabxss"
version = "0.1.0"
edition = "2021"

[dependencies]
error-chain = "0.12.4"
reqwest = "0.11.22"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
url = "2.2.2"
regex = "1.11.0"
urlencoding = "2.1.3"
clap = { version = "3.0", features = ["derive"] }

